global:
  resolve_timeout: 5m
route:
  group_by: [service]
  group_wait: 30s
  receiver: bespinian-slack
  routes:
    - receiver: bespinian-slack
receivers:
  - name: bespinian-slack
    slack_configs:
      - api_url: "https://hooks.slack.com/services/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"
        send_resolved: true
        title: "{{ .CommonAnnotations.title }}"
        text: "<!channel> {{ .CommonAnnotations.message }}"
