apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-cm
  labels:
    app: application-monitoring
    component: application-grafana
data:
  datasources.yml: |
    {
      "apiVersion": 1,
      "datasources": [
        {
          "access": "proxy",
          "editable": false,
          "name": "prometheus",
          "orgId": 1,
          "type": "prometheus",
          "url": "http://prometheus:9090",
          "version": 1
         }
      ]
    }
