apiVersion: v1
kind: Service
metadata:
  labels:
    app: application-monitoring
    component: application-grafana
  name: grafana
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    component: application-grafana
