{
 "title": "notification-api",
 "description": "notification-api metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pod", "query": "label_values(pod)" }
  ]
 },
 "panels": [
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(restify_path_count{pod=\"$pod\"}[1m])",
     "legendFormat": "{{$pod}}"
    }
   ]
  },
  {
   "title": "Main paths",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(rate(restify_path_count{pod=\"$pod\"}[1m])) by (path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Response time (95th percentile)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(restify_path_duration_bucket{pod=~\"$pod\"}[1m])) by (le))",
     "legendFormat": "{{$pod}}"
    }
   ]
  },
  {
   "title": "Resp. time / path",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(restify_path_duration_bucket{pod=~\"$pod\"}[1m])) by (path, le))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "restify_status_codes{pod=~\"$pod\"}",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "404 paths",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "restify_path_count{status_code=\"404\",pod=~\"$pod\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "500 paths",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "restify_path_count{status_code=\"500\",pod=~\"$pod\"}",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Status codes rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(restify_status_codes{pod=~\"$pod\"}[1m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Response time / Status codes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(restify_path_duration_bucket{pod=~\"$pod\"}[1m])) by (status_code, le))",
     "legendFormat": "{{status_code}}"
    }
   ]
  }
 ]
}