apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-cm
  labels:
    app: application-monitoring
    component: application-grafana
data:
  grafana.ini: |
    [auth.anonymous]
    enabled = true
    org_name = Main Org.
