apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBindingList
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: application-monitoring
      namespace: notification
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: application-monitoring
    subjects:
      - kind: ServiceAccount
        name: application-monitoring-prometheus
        namespace: application-monitoring
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: application-monitoring
      namespace: application-monitoring
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: application-monitoring
    subjects:
      - kind: ServiceAccount
        name: application-monitoring-prometheus
        namespace: application-monitoring
