apiVersion: v1
kind: Service
metadata:
  labels:
    component: notification-db-cluster
    app: notification
  name: notification-db-cluster
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    component: notification-db-cluster
