apiVersion: v1
kind: Service
metadata:
  labels:
    name: notification-mq
    app: notification
  name: notification-mq
spec:
  ports:
    - name: epmd
      port: 4369
    - name: node
      port: 5672
    - name: dist
      port: 25672
    - name: management
      port: 15672
  selector:
    component: notification-mq
