apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: notification-ui-ingress
  labels:
    app: notification
spec:
  tls:
    - hosts:
        - notification.bespinian.io
      secretName: notification-ui-secret
  rules:
    - host: notification.bespinian.io
      http:
        paths:
          - path: /*
            backend:
              serviceName: notification-ui
              servicePort: 80
