apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notification-ui-ingress
  labels:
    app: notification
spec:
  tls:
    - hosts:
        - notification.bespinian.io
      secretName: notification-ui-secret
  rules:
    - host: notification.bespinian.io
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: notification-ui
                port:
                  number: 80
