apiVersion: v1
kind: Service
metadata:
  name: notification-ui
  labels:
    name: notification-ui
    app: notification
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    component: notification-ui
