apiVersion: v1
kind: Service
metadata:
  labels:
    name: notification-db
    app: notification
  name: notification-db
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    component: notification-db
